server:
  port: 9090

#logging:
#  level:
#    root: DEBUG

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/sql_q5
    username: postgres
    password: root
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
